[data]
reference=./data/reference
uploads=./data/uploads
models=./data/models


[database]
uri=postgres://user:passwd@host:port/procas12f
;uri=./genes.db

[web]
host=0.0.0.0
port=5000
static=./frontend/dist
